# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogsetextg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(290, 240)
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(30, 30, 100, 30))
        self.name.setObjectName("name")
        self.tag = QtWidgets.QComboBox(Dialog)
        self.tag.setGeometry(QtCore.QRect(160, 30, 100, 30))
        self.tag.setObjectName("tag")
        self.count = QtWidgets.QSpinBox(Dialog)
        self.count.setGeometry(QtCore.QRect(160, 80, 100, 30))
        self.count.setMaximum(2147483647)
        self.count.setObjectName("count")
        self.company = QtWidgets.QLineEdit(Dialog)
        self.company.setGeometry(QtCore.QRect(30, 80, 100, 30))
        self.company.setObjectName("company")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(110, 180, 70, 30))
        self.ok.setObjectName("ok")
        self.llimit = QtWidgets.QLineEdit(Dialog)
        self.llimit.setGeometry(QtCore.QRect(30, 130, 100, 30))
        self.llimit.setObjectName("llimit")
        self.rlimit = QtWidgets.QLineEdit(Dialog)
        self.rlimit.setGeometry(QtCore.QRect(160, 130, 100, 30))
        self.rlimit.setObjectName("rlimit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name.setPlaceholderText(_translate("Dialog", "名称"))
        self.company.setPlaceholderText(_translate("Dialog", "厂商"))
        self.ok.setText(_translate("Dialog", "确定"))
        self.llimit.setPlaceholderText(_translate("Dialog", "下限"))
        self.rlimit.setPlaceholderText(_translate("Dialog", "上限"))
