# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogset.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 290)
        self.listtag = QtWidgets.QListWidget(Dialog)
        self.listtag.setGeometry(QtCore.QRect(30, 60, 240, 200))
        self.listtag.setObjectName("listtag")
        self.ltag = QtWidgets.QLabel(Dialog)
        self.ltag.setGeometry(QtCore.QRect(30, 30, 90, 30))
        self.ltag.setObjectName("ltag")
        self.bptag = QtWidgets.QPushButton(Dialog)
        self.bptag.setGeometry(QtCore.QRect(120, 30, 50, 30))
        self.bptag.setObjectName("bptag")
        self.bmtag = QtWidgets.QPushButton(Dialog)
        self.bmtag.setGeometry(QtCore.QRect(170, 30, 50, 30))
        self.bmtag.setObjectName("bmtag")
        self.bstag = QtWidgets.QPushButton(Dialog)
        self.bstag.setGeometry(QtCore.QRect(220, 30, 50, 30))
        self.bstag.setObjectName("bstag")
        self.bmgoods = QtWidgets.QPushButton(Dialog)
        self.bmgoods.setGeometry(QtCore.QRect(450, 30, 50, 30))
        self.bmgoods.setObjectName("bmgoods")
        self.lgoods = QtWidgets.QLabel(Dialog)
        self.lgoods.setGeometry(QtCore.QRect(310, 30, 90, 30))
        self.lgoods.setObjectName("lgoods")
        self.listgoods = QtWidgets.QListWidget(Dialog)
        self.listgoods.setGeometry(QtCore.QRect(310, 60, 240, 200))
        self.listgoods.setObjectName("listgoods")
        self.bsgoods = QtWidgets.QPushButton(Dialog)
        self.bsgoods.setGeometry(QtCore.QRect(500, 30, 50, 30))
        self.bsgoods.setObjectName("bsgoods")
        self.bpgoods = QtWidgets.QPushButton(Dialog)
        self.bpgoods.setGeometry(QtCore.QRect(400, 30, 50, 30))
        self.bpgoods.setObjectName("bpgoods")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ltag.setText(_translate("Dialog", "标签"))
        self.bptag.setText(_translate("Dialog", "+"))
        self.bmtag.setText(_translate("Dialog", "-"))
        self.bstag.setText(_translate("Dialog", "set"))
        self.bmgoods.setText(_translate("Dialog", "-"))
        self.lgoods.setText(_translate("Dialog", "货物"))
        self.bsgoods.setText(_translate("Dialog", "set"))
        self.bpgoods.setText(_translate("Dialog", "+"))
