# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogin(object):
    def setupUi(self, Dialogin):
        Dialogin.setObjectName("Dialogin")
        Dialogin.resize(260, 190)
        self.count = QtWidgets.QSpinBox(Dialogin)
        self.count.setGeometry(QtCore.QRect(130, 80, 100, 30))
        self.count.setMinimum(1)
        self.count.setMaximum(2147483647)
        self.count.setObjectName("count")
        self.type = QtWidgets.QComboBox(Dialogin)
        self.type.setGeometry(QtCore.QRect(130, 30, 100, 30))
        self.type.setObjectName("type")
        self.ltype = QtWidgets.QLabel(Dialogin)
        self.ltype.setGeometry(QtCore.QRect(30, 30, 100, 30))
        self.ltype.setObjectName("ltype")
        self.lcount = QtWidgets.QLabel(Dialogin)
        self.lcount.setGeometry(QtCore.QRect(30, 80, 100, 30))
        self.lcount.setObjectName("lcount")
        self.OK = QtWidgets.QPushButton(Dialogin)
        self.OK.setGeometry(QtCore.QRect(80, 130, 100, 30))
        self.OK.setObjectName("OK")

        self.retranslateUi(Dialogin)
        QtCore.QMetaObject.connectSlotsByName(Dialogin)

    def retranslateUi(self, Dialogin):
        _translate = QtCore.QCoreApplication.translate
        Dialogin.setWindowTitle(_translate("Dialogin", "进货"))
        self.ltype.setText(_translate("Dialogin", "类型："))
        self.lcount.setText(_translate("Dialogin", "数量："))
        self.OK.setText(_translate("Dialogin", "确定"))
