# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 600)
        self.bsettings = QtWidgets.QPushButton(Form)
        self.bsettings.setGeometry(QtCore.QRect(30, 530, 150, 40))
        self.bsettings.setObjectName("bsettings")
        self.bin = QtWidgets.QPushButton(Form)
        self.bin.setGeometry(QtCore.QRect(30, 30, 150, 40))
        self.bin.setObjectName("bin")
        self.bout = QtWidgets.QPushButton(Form)
        self.bout.setGeometry(QtCore.QRect(30, 80, 150, 40))
        self.bout.setObjectName("bout")
        self.blog = QtWidgets.QPushButton(Form)
        self.blog.setGeometry(QtCore.QRect(30, 130, 150, 40))
        self.blog.setObjectName("blog")
        self.messageq = QtWidgets.QListWidget(Form)
        self.messageq.setGeometry(QtCore.QRect(210, 30, 720, 540))
        self.messageq.setObjectName("messageq")
        self.bget = QtWidgets.QPushButton(Form)
        self.bget.setGeometry(QtCore.QRect(30, 180, 150, 40))
        self.bget.setObjectName("bget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "仓库管理系统"))
        self.bsettings.setText(_translate("Form", "设置"))
        self.bin.setText(_translate("Form", "入库"))
        self.bout.setText(_translate("Form", "出库"))
        self.blog.setText(_translate("Form", "记录"))
        self.bget.setText(_translate("Form", "库存"))
